// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// Next.js convention: .env.local holds real local secrets and isn't committed; load it after
// .env (and let it win) so `prisma` CLI commands see the same DATABASE_URL the app itself uses.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
